# pre-commit file
# https://pre-commit.com/
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_tfsec
        args:
          - >
            --args=-m CRITICAL
      - id: terraform_docs
        args:
          - --hook-config=--create-file-if-not-exist=true
  # - repo: https://github.com/kynan/nbstripout
  #   rev: 0.6.1
  #   hooks:
  #     - id: nbstripout
