name: attestation-generation
on: [push]
permissions:
  id-token: write
  contents: read
  attestations: write
jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutCode
        uses: actions/checkout@v4
      - name: Linting
        uses: chartboost/ruff-action@v1
        with:
          src: ./python-example
          args: 'format --check'
  build:
    runs-on: ubuntu-latest
    needs: lint-and-check
    steps:
      - name: CheckoutCode
        uses: actions/checkout@v4
      - name: SetUpDockerBuildx
        uses: docker/setup-buildx-action@v3
        # with:
        #   buildkitd-config: buildkitd.toml
        #   buildkitd-flags: '--debug'
      - uses: docker/build-push-action@v5
        name: BuildAndPushDockerImage
        id: build
        with:
          push: false
          file: python-example/Dockerfile
          context: ./python-example
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: github-actions-python:dev
          outputs: type=docker,dest=/tmp/myimage.tar
      - name: Create Attestation
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: 'github-actions-python:dev'
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
      - name: UploadArtifact
        uses: actions/upload-artifact@v4
        # env:
        #   NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt # https://github.com/actions/upload-artifact/issues/129
        with:
          name: myimage
          path: /tmp/myimage.tar
